export const CHANGE_INDEX_VUE = 'CHANGE_INDEX_VUE';
export const CHANGE_STUFF = 'CHANGE_STUFF';
export const CHANGE_SCALE = 'CHANGE_SCALE';
export const MAIL_AMOUNT = 'MAIL_AMOUNT';
export const MAIL_TYPE = 'MAIL_TYPE';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';

export const VUE = {
    INDEX: 1,
    WHY: 2,
    DISCOVER: 3,
    TRANSITION_MAIL: 4,
    MAIL_QUANTITY: 5,
    MAIL_TYPE: 6,
    MAIL_DATA: 7,
    TRANSITION_TRAFIC: 8,
    TRAFIC_BW: 9,
    TRAFIC_SERV: 10,
    TRANSITION_ENERGY: 11,
    FUTUR: 12,
    FINAL: 13
};
